sonar.projectKey=e-commerce-be
sonar.projectName=E-Commerce Backend API
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.test.ts

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json

sonar.javascript.lcov.reportPaths=coverage/lcov.info